#ifndef EP_CUSTOMTYPES_H
#define EP_CUSTOMTYPES_H

typedef enum EP_Report_Types{
    EP_EXPENSE_TODAY_EXPENSE_TIME = 0,
    EP_EXPENSE_THIS_WEEK_TIME = 1,
    EP_EXPENSE_THIS_MONTH_TIME = 2,
    EP_EXPENSE_THIS_YEAR_TIME = 3,
    EP_EXPENSE_ALL_TIME_TIME = 4,
    EP_EXPENSE_CUSTOM_TIME = 5,
    EP_EXPENSE_TRANSPORT_TYPE = 6,
    EP_EXPENSE_FOOD_TYPE = 7,
    EP_EXPENSE_CLOTHES_TYPE = 8,
    EP_EXPENSE_UTILITY_TYPE = 9,
    EP_EXPENSE_BANK_TYPE = 10,
    EP_EXPENSE_OTHER_TYPE = 11,
    EP_INCOME_TODAY = 12,
    EP_INCOME_THIS_WEEK = 13,
    EP_INCOME_THIS_MONTH = 14,
    EP_INCOME_THIS_YEAR = 15,
    EP_INCOME_ALL_TIME = 16,
    EP_INCOME_CUSTOM = 17
}EPReportType;

#endif // EP_CUSTOMTYPES_H
